config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get '/about', to: 'welcome#about'
  get '/team', to: 'welcome#team'

  resource :dashboard, only: :show

  resources :users, controller: 'users', only: [:new, :create, :edit, :update]
  resources :foods, only: [:new, :create]
  resources :devices, only: :new
  resources :meals, only: [:create, :update, :destroy]
  resources :sessions, only: :index
end

app/views/shared/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<div class="js-menu-screen menu-screen"></div>
<div id="main-nav">
  <img src="http://i.imgur.com/96GXzhc.png" id="logoImg">
  <div class="logoContainer">
    <%= link_to 'PLADEL', root_path, class: 'navLogo', id: 'logo'%>
  </div>

  <button type="button" class="js-menu-trigger sliding-menu-button">
    <img src="http://i.imgur.com/z0T2YKN.png" alt="">
  </button>

  <nav class="js-menu sliding-menu-content">
    <ul>
      <% if signed_in? %>
        <li>
        <%= link_to 'Sign out', sign_out_path, method: :delete, class: 'navLink' %>
      </li>
      <li>
        <%= link_to 'Sync data', sessions_path, method: :get, class: 'navLink', remote: true %>
      </li>
      <li>
        <%= link_to 'Foods', new_food_path, class: 'navLink' if controller.controller_name == 'dashboards' %>
      </li>
      <li>
        <%= link_to 'Apps', "https://app.validic.com/#{ENV["VALIDIC_ORGANIZATION_ID"]}/#{current_user.token}", class: 'navLink', target: '_blank' if controller.controller_name == 'dashboards' %>
      </li>

        <% if controller.controller_name == 'welcome' %>
        <li>
          <%= link_to 'Dashboard', dashboard_path, class: 'navLink' %>
        </li>
        <li>
          <%= link_to 'About', about_path, class: 'navLink' %>
        </li>
        <li>
          <%= link_to 'Team', team_path, class: 'navLink' %>
        </li>
        <% end %>
      <% else %>
      <li>
        <%= link_to 'About', about_path, class: 'navLink' %>
      </li>
      <li>
        <%= link_to 'Team', team_path, class: 'navLink' %>
      </li>
      <li>
        <%= link_to 'Sign in', sign_in_path, class: 'navLink' %>
      </li>
      <% end %>
    </ul>
  </nav>
</div>