config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get '/about', to: 'welcome#about'
  get '/team', to: 'welcome#team'

  resource :dashboard, only: :show

  resources :users, controller: 'users', only: [:new, :create, :edit, :update]
  resources :foods, only: [:new, :create]
  resources :devices, only: :new
  resources :meals, only: [:create, :update, :destroy]
  resources :sessions, only: :index
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  def composite_percent(user)
    (user.nutrition_composite * 100).round
  end

  def nutrition_composite_empty?(user)
    composite_percent(user) == 0
  end

  def movement_composite_empty?(user)
    (user.movement_composite / 100).round == 0
  end

  def sleep_composite_empty?(user)
    (user.sleep_composite / 0.30).round == 0
  end

  def health_gpa_percent_denominator(user)
    denominator = 0
    composites = [nutrition_composite_empty?(user),
                  movement_composite_empty?(user),
                  sleep_composite_empty?(user)]
    composites.each do |composite|
      denominator += 1 if composite == false
    end
    denominator == 0 ? 1 : denominator
  end
end

app/views/dashboards/show.html.erb
<% provide(:title, 'Dashboard') %>
<div class="dashboard">
  <div id="firstSectionWrapper">
    <%= render 'shared/modal' %>

    <div class="letter overall"><%= current_user.health_gpa %></div>

    <div class="dataTime">
      <a href="#">DAY</a>
      <a href="#">WEEK</a>
      <a href="#">MONTH</a>
      <a href="#">YEAR</a>
    </div>

    <div id="doughnutChart" class="chart">
      <p class="gpaTitle">GPA</p>
      <div class="checked animated tada">
        <%= image_tag 'check.png' %>
      </div>
      <div class="closed animated tada">
        <%= image_tag 'close.png' %>
      </div>
    </div>


    <div class="scoresWrapper">
        <div class="movement tooltip-item">
          <img src="http://i.imgur.com/zSX5ZBP.png">
          <p class="percentage"><%= "#{(current_user.movement_composite / 100).round}%" %></p>
          <p class="category">Movement</p>
          <!-- <div class="tooltip">
            <p>Your movement score is calculated by the amount of movement and intensity. It is calculated daily, weekly and all time. You can toggle between daily, weekly, monthly and all time by clicking on the buttons below the chart.</p>
          </div> -->
        </div>

        <div class="sleep tooltip-item">
          <img src="http://i.imgur.com/C1YxKV5.png">
          <p class="percentage"><%= "#{(current_user.sleep_composite / 0.30).round}%" %></p>
          <p class="category">Sleep</p>
          <!-- <div class="tooltip">
            <p>Your sleep score is calculated by the amount of sleep and quality. It is calculated daily, weekly and all time. You can toggle between daily, weekly, monthly and all time by clicking on the buttons below the chart.</p>
          </div> -->
        </div>

        <div class="nutrition tooltip-item">
          <img src="http://i.imgur.com/yIaczgi.png">
          <p class="percentage"><%= "#{composite_percent(current_user)}%" %></p>
          <p class="category">Nutrition</p>
          <!-- <div class="tooltip">
            <p>Your nutrition score is calculated by the percentage of meals eaten daily, weekly and all time. You can toggle between daily, weekly, monthly and all time by clicking on the buttons below the chart.</p>
          </div> -->
        </div>
    </div>

  </div>


    <div class="meal-reporting">
      <div class="meals tooltip-item">
          <!-- <div class="tooltip">
            <p>To report and track your meals you can click on each meal icon and select complete or incomplete. The meals will highlight when reported and you will see new empty icons appear in case you need to add another meal.</p>
        </div> -->
      </div>

      <div class="meal_buttons">
        <%= link_to 'ate healthy', meal_path(current_user.meals.last), method: :patch, id: 'checkButton', remote: true %></li>
        <%= link_to 'ate poorly', meal_path(current_user.meals.last), method: :delete, id: 'xButton', remote: true %> </li>
      </div>

      <div class="mealsLoggedWrqpper">
        <p class="mealsLogged">
          MEALS TODAY: <span class="meal-logging"><%= Meal.today(current_user).count - 1 %></span>
        </p>
      </div>

    </div>
</div>

  <script>
$(function(){
  $("#doughnutChart").drawDoughnutChart([
    { title: "Overall GPA",         value : <%= ((current_user.sleep_composite / 0.3).round + (current_user.movement_composite / 100).round + composite_percent(current_user)) / health_gpa_percent_denominator(current_user) %>,  color: "#75C9BC" },
    { title: "Room for improvement", value:  100 - <%= ((current_user.sleep_composite / 0.3).round + (current_user.movement_composite / 100).round + composite_percent(current_user)) / health_gpa_percent_denominator(current_user) %>,   color: "#585858" },
  ]);
});
  </script>